name: musiq
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  provider: ^6.0.3
  audio_video_progress_bar: ^0.10.0
  audio_service: ^0.18.9
  rxdart: ^0.27.7
  internet_connection_checker: ^0.0.1+4

  flutter_native_image: ^0.0.6+1

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  image_picker: ^0.8.5+3
  google_fonts: ^3.0.1
  http: ^0.13.4
  just_audio: ^0.9.24
  # just_audio_background: any
  connectivity_plus: ^2.3.5
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.3
  objectbox: ^1.7.1
  objectbox_flutter_libs: any
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  get_it: ^7.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.11
  objectbox_generator: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.5.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#000000"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/
    - assets/images/fav/
    - assets/images/artist/
    - assets/images/default/
    - assets/images/artistList/
    - assets/images/playlist/
    - assets/icons/
    - assets/images/homepage/
    - assets/song/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
