name: musiq
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  audio_video_progress_bar: ^0.10.0
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  audio_service: ^0.18.9
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.9
  get_it: ^7.1.2
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.18.0
  just_audio: ^0.9.24
  just_audio_background: ^0.0.1-beta.9
  objectbox: ^1.7.1
  objectbox_flutter_libs: any
  palette_generator: ^0.3.3+2
  path: ^1.8.1
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.3
  razorpay_flutter: ^1.3.4
  rxdart: ^0.27.7
  flutter_image_compress: ^1.1.3
  share_plus: ^6.3.0
  flutter_cache_manager: ^3.3.0
  audio_session: ^0.1.11
  equalizer_flutter: ^0.0.1
  dependencies:
  # audio_waveforms: ^1.0.4
  # just_waveform: ^0.0.4
  flutter_audio_waveforms: ^1.2.1+8
  # audio_wave: ^0.1.5
  # wave_progress_bars: ^0.1.0
  # flutter_animated_dialog: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.11
  # dart_code_metrics: ^5.5.1
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#000000"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/

    - assets/images/default/

    - assets/icons/

    - assets/song/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
